AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2One:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b74f796d330ab49c
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y nodejs git
          git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git /home/ec2-user/app
          cd /home/ec2-user/app
          npm install
          node server.js > server.log 2>&1 &

  EC2Two:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b74f796d330ab49c
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y nodejs git
          git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git /home/ec2-user/app
          cd /home/ec2-user/app
          npm install
          node server.js > server.log 2>&1 &

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyALB
      Subnets:
        - subnet-07a49735496e5a18b
        - subnet-0aba2dfb95814920f
        - subnet-0712214530bc7d4b1
      SecurityGroups:
        - !Ref SecurityGroup
      Scheme: internet-facing

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: HTTP
      VpcId: vpc-07abf5cb2f6a05900
      TargetType: instance
      Targets:
        - Id: !Ref EC2One
        - Id: !Ref EC2Two

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
